services:
  tsunami:
    build: tsunami-security-scanner/.
    image: ghcr.io/samma-io/tsunami:latest
    volumes:
      - ./out/:/out/
    command: --ip-v4-target=158.174.104.17 --scan-results-local-output-format=JSON --scan-results-local-output-filename=/out/tsunami-output.json
  samma-logger:
    image: sammascanner/logger:0.1
    volumes:
      - ./out/:/out/
    environment:
      - FILE=tsunami-output.json
      - PARSER=tsunami
      - SAMMA_IO_SCANNER=tsunami
      - SAMMA_IO_ID=1234
      - SAMMA_IO_TAGS=scanner,prod
      - SAMMA_IO_JSON={}
      - TARGET_ID=
      - WRITE_TO_FILE=true
      - NATS_ENABLED=False
      - NATS_URL=nats://localhost:4222
      - NATS_SUBJECT=scans
